Реализовать весь требуемый функционал
TBKaGOC/java-filmorate pull request #16
Opened 2024-10-14 19:27 UTC by TBKaGOC

Выполнен в полном объёме весь функционал заданий от одного до четырёх поинтов. Добавлены две новые структуры и реализованы из взаимодействия со старыми.

2024-10-17 18:51 UTC, EugeneLenkevich requested changes
Привет, Тимур! Спасибо за PR.

Видно что проделана большая работа, с этнтузиазмом и вообще интересно код проверять. 

В целом если
 - В первую очередь надо постараться делать работу единообразно, одинаковые вещи делать одним способом, выбрать в команде и придерживаться его на конкретном проекте. Это сильно упрощает поддержку кода
 - Запросы в БД в цикле - это потенциальные проблемы с производительностью, лучше все необходимые данные получать одним запросом, да он будет посложнее, но, и, в итоге, это будет и проще и быстрее работать. 
 - Логирование надо бы причесать, не надо вручную строки форматировать, log4j это сам умеет


Плюс еще какие то мелочи, постарался се основное отметить комментариями, посмотри пожалуйста. В целом все здорово, но надо бы шлифануть :)

2024-10-17 18:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/dto/FilmDto.java
> +    LocalDate releaseDate;
+ private, и для id, лучше не забывать :)

2024-10-17 18:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/dto/ReviewDto.java
> +    String content;
Опять таки, тут надо бы private, если он и генерируется через аннотации, то надо бы к единому виду  dto привести, а то как то вразнобой, лучше когда все сделано в едином стиле, так код проще воспринимать :)

2024-10-17 18:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
А подходит ли для данной ситуации непроверяемое исключение?
Пользователь ввел некорректные данные и система ничего не нашла - вполне себе штатная ситуация, пусть тут будет проверяемое исключение :)
extends Exception

Так же. А нужна ли аннотация, подключающая лог, над исключением `@Slf4j`. Внутри исключения нечего логировать, но аннотация включит генерацию кода в рантайме, будет создан ненужный логгер и пр, но зачем если можно не создавать :)

2024-10-17 18:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/mapper/DirectorMapper.java
> +    public static DirectorDto mapToDirectorDto(Director director) {
А соседний маппер сделан как бин. опять такие не стоит делать одно и то же разными способами,  не надо увеличивать энтропию системы на ровном месте, пусть будет какой то единый стиль :)

![image](https://github.com/user-attachments/assets/5fc06977-6e19-4a24-a3d0-d1b3296900e6)

2024-10-17 18:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private LinkedHashSet<Director> directors;
private Set<Director> directors;

Пусть тут будет абстрактный интерфейс а не конкретный тип коллекции, хоть немного но код гибче. И покороче, это же часто ненужные детали реализации :)

2024-10-17 18:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        log.debug("Получаем записи о всех режиссерах");
Тут стоит взять уровень не debug, а info, это же логирование  бизнес-операций. 
debug - это уровень отладки, на нем лучше выводить какие то технические детали

- error - нештатные ситуации
- warn - штатные ошибки, та же валидация
- info - бизнес операции, плюс сюда в лог стоит включать какие то базовые идентификаторы, по которым можно будет сопоставлять строки лога с конкретными сущностями
- debug - дополнительная техническая информация, можно содержимое dto распечатывать, например (в реальном приложении только с этим аккуратно, не стоит так раскрывать какую то конфиденциальную информацию)
- trace это совсем какие то мелочи логируются, может даже строчки кода, но нам не надо это особо 

Несколько примерчиков

log.info Обновление сущности, id=
log.debug dto= {}
log.info Сущность успешно создана

log.warn Ошибка валидации, значение {} недопустимо
log.error Нет соединения с БД


Примерно вот так. Я конечно не призываю все сейчас логирование пере
писывать по такому образцу, но когда все залогировано именно гораздо удобнее по логам ориентироваться, но уровень бы тут в любом случае поднять бы до info

2024-10-17 18:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        for (Integer i : genreStorage.findGenresIdsByFilmId(film.getId())) {
У нас тут два вложенных цикла и на каждой итерации мы по несколько раз лезем в базу. Само по себе обращение к БД - достаточно дорогая операция так тут мы еще и делаем кучку запросов со сложность O(n^2). Если записей в табличке будет много то это обязательно отрицательно скажется на производительности, тот хочется уменьшить количество запросов. Можно же не по одной записи по id вытаскивать а сразу несколько по списку id, как пример, но может и что то другое получится придумать :)

2024-10-17 18:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        LinkedHashSet<Director> directors = new LinkedHashSet<>();
`Set<Director> directors = ...`

Лучше избавляться от конкретных реализаций коллекций в типах переменных, пусть будут абстрактные интерфейсы :)

2024-10-17 18:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                directors.add(director);
А вот тут у нас опять таки обращение в БД в цикле, это хотелось бы сразу оптимизировать
Плюс, мы молча проглатываем исключение, то есть если у нас что то идет не так то мы даже знать не будем :)
Но, кажется, что если заменить цикл на один запрос то и потребности в этом перехвате исключения и не будет

2024-10-17 18:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.debug(String.format("Ищем лайки фильма %s", film.getName()));
log.debug("Ищем лайки фильма {}", film.getName());

Логгер и так умеет подставлять параметры в строки
Это еще и более оптимально так как такие выражения не будут вычисляться вовсе в случае если не включен соответствующий уровень логирования. В случае же с String.format выражения будут выполняться всегда :)

2024-10-17 18:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted((e1, e2) -> {
Сортировка - это обязанность хранилища

У каждого слоя есть свои обязанности, если простыми словами то вот так
- контроллеры маршрутизируют сами запросы на наши сервисы
- сервисы оперируют понятиями предметной области, в них и содержится вся бизнес-логика 
- хранилище же занимается вопросами хранения, фильтрации и выборки данных

В общем эту сортировку делать бы в хранилище

2024-10-17 18:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationsService.java
> +            likedFilms = new HashSet<>(filmStorage.getUsersLikedFilms(id));
Опять таки запросы в цикле :)

2024-10-17 18:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            return storage.getReviews(count)
return storage.getReviews(count)
                    .stream()
                    .limit(count)

А зачем нам тут limit, мы же в хранилище уже передали count, наверное оно столько записей и должно вернуть, или нет? :)

2024-10-17 18:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        getUser(userId);//for check if exist
Есть такое правило - если хочется написать комментарий, который поясняет логику работы кода, то  скорее всего этот код стоит переписать так как он неочевиден :)
Тут наверно стоит явно указать что мы проверяем и что делаем если условие не совпадает
if (isValid()) {
  throw new ....
}

2024-10-17 18:51 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/in_memory/InMemoryFilmStorage.java
>  public class InMemoryFilmStorage implements FilmStorage {
А что если эти старые хранилища удалить чтобы не поддерживать их код, у нас же сейчас есть хранение в БД, самим же проще будет :)

2024-10-17 18:51 UTC, EugeneLenkevich commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserStorageTests.java
> +        //Реализация в InMemoryUserStorage сломана, её вообще можно удалить
Таки да и ничего не мешает это сделать, вся история если что есть в гите :)

2024-10-18 07:42 UTC, felixoff commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +
В путях лучше использовать тире а не нижнее подчёркивания

2024-10-18 07:42 UTC, felixoff commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    @PutMapping("/{id}/dislike/{userId}")
Пути не пишут camelCase

2024-10-18 08:40 UTC, EugeneLenkevich requested changes
Привет! спасибо за исправления

Вижу много правок по наведению красоты, все гут, единственное

на месте остались запросы в циклах, например вот этот, от такого лучше избавляться, заменить на один большой запрос к БД, а в сервисе уже разобрать по объектам его ответ
![image](https://github.com/user-attachments/assets/bf445b4e-031b-490b-b43e-0a020366d8ff)

далее, логирование
- логирование бизнес операций хотелось бы видеть в info, это важные моменты для понимания логики происходящего 
- String.format убрать бы, не нужен он тут
![image](https://github.com/user-attachments/assets/d4870668-2c02-42d4-af60-ea48f198f736)

Ну и часть тестов так понимаю отключены оказались, лучше поднять, не критично но очень желательно :)

Может каких то изменений в ПР-е, что то не залито в ветку оказалось, посмотрите, командой, пожалуйста

2024-10-18 19:40 UTC, EugeneLenkevich approved these changes

2025-06-30 12:27 UTC, merged